=== littlebyteorg/appledb/schemas/osFiles.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apple OS",
    "description": "Description of an Apple operating system release",
    "$ref": "#/definitions/os",
    "type": "object",
    "required": ["osStr", "version"],
    "definitions": {
        "os": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "osStr":         {"type": "string"},
                "version":       {"type": "string", "not": { "pattern": "FIXME" }},
                "iosVersion":    {"type": "string"},
                "safariVersion": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "build":         {"type": "string"},
                "restoreVersion": {"type": "string"},
                "buildId":       {"type": "string", "format": "uuid"},
                "uniqueBuild":   {"type": "string"},
                "key":           {"type": "string"},
                
                "bridgeOSBuild":    {"type": "string"},
                "embeddedOSBuild":  {"type": "string"},
                "basebandVersions": {
                    "type":"object",
                    "additionalProperties": true
                },
                "buildTrain":    {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },

                "released":     {"anyOf": [
                    {"type": "string", "format": "date-time"},
                    {"type": "string", "format": "date"},
                    {"type": "string", "pattern": "^\\d{4}-\\d{2}$"},
                    {"type": "string", "pattern": "^\\d{4}$"},
                    {"type": "string", "maxLength": 0}
                ]},
                "rc":           {"type": "boolean"},
                "beta":         {"type": "boolean"},
                "bsi":          {"type": "boolean"},
                "rsr":          {"type": "boolean"},
                "internal":     {"type": "boolean"},
                "hideFromLatestVersions": {"type": "boolean"},
                "notes":        {"type": "string"},
                "releaseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "enterpriseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "securityNotes": {
                    "anyOf": [
                        {"type": "null"},
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },

                "preinstalled": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "preinstalledOS": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "signed": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "deviceMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "osMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "ipd": {
                    "type": "object",
                    "properties": {
                        "AudioAccessory": {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "AppleTV":  {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPhone":   {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPad":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPod":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        }
                    },
                    "additionalProperties": {
                        "anyOf": [
                            {"type": "string", "format": "uri"},
                            {"$ref": "#/definitions/sourceLink"}
                        ]
                    }
                },
                "createDuplicateEntries": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "allOf": [
                            {"$ref": "#/definitions/os"},
                            {"type": "object", "properties": {"createDuplicateEntries": false}}
                        ]
                    }
                },
                "sdks": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "beta": {"type": "boolean"},
                            "build": {"type": "string"},
                            "buildId": {"type": "string", "format": "uuid"},
                            "osStr": {"type": "string"},
                            "rc": {"type": "boolean"},
                            "version": {"type": "string"}
                        }
                    }
                },
                "appledbWebImage": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "id": {"type": "string"},
                        "align": {"type": "string"}
                    }
                },
                "appledbUrl": {"type": "string"},
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "links", "deviceMap"],
                        "properties": {
                            "type": {"enum": ["ipsw", "ota", "update", "recovery", "sfr", "kdk", "installassistant", "combo", "pkg", "aar", "dmg", "exe", "appx", "apk", "xip", "tar", "bin", "ipa", "xpi", "msi", "zip", "smi"]},
                            "arch": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "deviceMap": {"$ref": "#/definitions/os/properties/deviceMap"},
                            "boardMap": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "osMap": {"$ref": "#/definitions/os/properties/osMap"},
                            "skipUpdateLinks": {"type": "boolean"},
                            "windowsUpdateDetails": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "updateId": {"type": "string", "format": "uuid"},
                                    "revisionId": {"type": "string", "pattern": "^\\w+$"}
                                }
                            },
                            "hashes": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "md5":      { "type": "string", "pattern": "^[0-9a-f]{32}$" },
                                    "sha1":     { "type": "string", "pattern": "^[0-9a-f]{40}$" },
                                    "sha2-256": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
                                    "sha2-512": { "type": "string", "pattern": "^[0-9a-f]{128}$" }
                                }
                            },
                            "links": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "$ref": "#/definitions/sourceLink"
                                }
                            },
                            "prerequisiteBuild": {
                                "anyOf": [
                                    {"type": "string"},
                                    {"type": "array", "minItems": 1, "items": {"type": "string"}}
                                ]
                            },
                            "systemImageId": {"type": "string", "format": "uuid"},
                            "size": {"type": "integer"}
                        }
                    }
                }
            }
        },
        "sourceLink": {
            "type": "object",
            "additionalProperties": false,
            "required": ["url", "active"],
            "properties": {
                "url": {"type": "string", "format": "uri"},
                "decryptionKey": {"type": "string"},
                "active": {"type": "boolean"},
                "catalog": {"enum": ["dev-beta", "public-beta"]}
            }
        }
    }
}

=== littlebyteorg/appledb/osFiles/bridgeOS/18x/18P52551s.json
{
    "osStr": "bridgeOS",
    "version": "5.0.1 beta",
    "build": "18P52551s",
    "released": "2020-10-28",
    "beta": true,
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,6",
        "iBridge2,7",
        "iBridge2,8",
        "iBridge2,10",
        "iBridge2,12",
        "iBridge2,14",
        "iBridge2,15",
        "iBridge2,16",
        "iBridge2,19",
        "iBridge2,20",
        "iBridge2,21",
        "iBridge2,22"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "http://swcdn.apple.com/content/downloads/16/13/001-58877-A_39XMCAVLFG/0dygc5fjj52xaox8r7c6n6niup2fe24a3y/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 441765045
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/4.x/4.0.2.json
{
    "osStr": "Safari",
    "version": "4.0.2",
    "released": "2009-07-08",
    "securityNotes": "https://support.apple.com/HT3666",
    "deviceMap": [
        "Safari (Windows)",
        "Safari (macOS)"
    ],
    "osMap": [
        "Mac OS X 10.4",
        "Mac OS X 10.5",
        "Windows XP",
        "Windows Vista",
        "Windows 7"
    ],
    "sources": [
        {
            "type": "exe",
            "deviceMap": [
                "Safari (Windows)"
            ],
            "osMap": [
                "Windows XP",
                "Windows Vista",
                "Windows 7"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/Safari4/061-6759.20090708.Lki98/SafariSetup.exe",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "2e74dc2c47d414f9f34d845965d7f6da"
            },
            "size": 28464416
        },
        {
            "type": "dmg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "Mac OS X 10.5"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/Safari4/061-6761.20090708.AsxpI/Safari4.0.2Leo.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "93d5a350d96bb0949039d35b415c0ccb"
            },
            "size": 41908858
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Rosetta/26x - 27.x/26B5101f.json
{
    "osStr": "Rosetta",
    "version": "27.2 beta 3",
    "build": "26B5101f",
    "released": "2026-10-05",
    "beta": true,
    "deviceMap": [
        "Rosetta"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Rosetta"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/40/17/142-35644-A_OF3A3JS9H8/sshhkqm294so85g8fx4j4b55zn96ucc971/RosettaUpdateAuto.pkg",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "a8ce20f0607cc11243a89daecc7bcd5400c47a22"
            },
            "size": 248723
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/QuickTime/7.x/7.6.8.json
{
    "osStr": "QuickTime",
    "version": "7.6.8",
    "released": "2010-09-15",
    "securityNotes": "http://support.apple.com/kb/HT4339",
    "deviceMap": [
        "QuickTime (Windows)"
    ],
    "osMap": [
        "Windows XP SP2",
        "Windows Vista",
        "Windows 7"
    ],
    "sources": [
        {
            "type": "exe",
            "deviceMap": [
                "QuickTime (Windows)"
            ],
            "osMap": [
                "Windows XP SP2",
                "Windows Vista",
                "Windows 7"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/QuickTime/061-8938.20100915.Qts3T/QuickTimeInstaller.exe",
                    "active": true
                }
            ]
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari Technology Preview/36.json
{
    "osStr": "Safari Technology Preview",
    "version": "36",
    "safariVersion": "11.0",
    "released": "2017-07-26",
    "beta": true,
    "releaseNotes": "https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-36",
    "deviceMap": [
        "Safari Technology Preview"
    ],
    "osMap": [
        "macOS 10.12",
        "macOS 10.13"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 10.12"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/091-23520-20170726-AC590232-714D-11E7-958D-19D4484DD6D5/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "19a04bdfb18e4cde87022bec0825797c",
                "sha1": "0db7654283aaf59027731d0104e03923e6ada388",
                "sha2-256": "cc3aae7d80ede050c50addc73cbbc7bab8a4a95787fb8bf29c73aa801f1d771d"
            },
            "size": 68984219
        },
        {
            "type": "dmg",
            "deviceMap": [
                "Safari Technology Preview"
            ],
            "osMap": [
                "macOS 10.13"
            ],
            "links": [
                {
                    "url": "https://secure-appldnld.apple.com/STP/091-23518-20170726-AC590278-714D-11E7-958D-1AD4484DD6D5/SafariTechnologyPreview.dmg",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "80d2e4abb9f4ce6c02444719f8c71c63",
                "sha1": "dbd1cae77c80752ba546bc921e0bfe00dbeed78f",
                "sha2-256": "9db2bb7740614d37f27c828f8bbd818e07d49de33fe79cbc4c0a68b96c7945b5"
            },
            "size": 68873635
        }
    ]
}

=== littlebyteorg/appledb/osFiles/macOS/14x - 10.10.x/14D2134.json
{
    "osStr": "OS X",
    "version": "10.10.3",
    "build": "14D2134",
    "buildTrain": "SUSyrahDomeHW",
    "released": "2015-04-16",
    "preinstalled": true,
    "appledbWebImage": {
        "id": "Yosemite",
        "align": "left"
    },
    "deviceMap": [
        "MacBookPro11,4",
        "MacBookPro11,5"
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Rosetta/24x - 15.x/24H232.json
{
    "osStr": "Rosetta",
    "version": "15.8.2",
    "build": "24H232",
    "released": "2026-10-26",
    "deviceMap": [
        "Rosetta"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Rosetta"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/30/59/142-50014-A_UYDNMT6JL0/i9up0ouxzbav9sact2pijsgm2yaf71y2nl/RosettaUpdateAuto.pkg",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "45fbab7d8de72de5fe71b4a422daa15510e95353"
            },
            "size": 451524
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/16.x/614D19.json
{
    "osStr": "Safari",
    "version": "16.3 beta 3",
    "build": "614D19",
    "released": "2023-01-18",
    "beta": true,
    "deviceMap": [
        "Safari (macOS)"
    ],
    "osMap": [
        "macOS 11"
    ],
    "sources": [
        {
            "type": "pkg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 11"
            ],
            "links": [
                {
                    "url": "http://swcdn.apple.com/content/downloads/49/20/032-35628-A_8UVCSDLEYN/dd389xfepd6uutlenj6gdsglhmm1c618ff/Safari16.3BigSurAutoSeed.pkg",
                    "active": false
                }
            ],
            "size": 128502643
        }
    ]
}
