=== littlebyteorg/appledb/schemas/osFiles.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Apple OS",
    "description": "Description of an Apple operating system release",
    "$ref": "#/definitions/os",
    "type": "object",
    "required": ["osStr", "version"],
    "definitions": {
        "os": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "osStr":         {"type": "string"},
                "version":       {"type": "string", "not": { "pattern": "FIXME" }},
                "iosVersion":    {"type": "string"},
                "safariVersion": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "build":         {"type": "string"},
                "restoreVersion": {"type": "string"},
                "buildId":       {"type": "string", "format": "uuid"},
                "uniqueBuild":   {"type": "string"},
                "key":           {"type": "string"},
                
                "bridgeOSBuild":    {"type": "string"},
                "embeddedOSBuild":  {"type": "string"},
                "basebandVersions": {
                    "type":"object",
                    "additionalProperties": true
                },
                "buildTrain":    {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },

                "released":     {"anyOf": [
                    {"type": "string", "format": "date-time"},
                    {"type": "string", "format": "date"},
                    {"type": "string", "pattern": "^\\d{4}-\\d{2}$"},
                    {"type": "string", "pattern": "^\\d{4}$"},
                    {"type": "string", "maxLength": 0}
                ]},
                "rc":           {"type": "boolean"},
                "beta":         {"type": "boolean"},
                "bsi":          {"type": "boolean"},
                "rsr":          {"type": "boolean"},
                "internal":     {"type": "boolean"},
                "hideFromLatestVersions": {"type": "boolean"},
                "notes":        {"type": "string"},
                "releaseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "enterpriseNotes": {
                    "anyOf": [
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },
                "securityNotes": {
                    "anyOf": [
                        {"type": "null"},
                        {"type": "string", "format": "uri"},
                        {"$ref": "#/definitions/sourceLink"}
                    ]
                },

                "preinstalled": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "preinstalledOS": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "signed": {
                    "anyOf": [
                        {"type": "boolean"},
                        {"type": "array", "items": {"type": "string"}}
                    ]
                },
                "deviceMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "osMap": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "uniqueItems": true
                },
                "ipd": {
                    "type": "object",
                    "properties": {
                        "AudioAccessory": {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "AppleTV":  {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPhone":   {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPad":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        },
                        "iPod":     {
                            "anyOf": [
                                {"type": "string", "format": "uri"},
                                {"$ref": "#/definitions/sourceLink"}
                            ]
                        }
                    },
                    "additionalProperties": {
                        "anyOf": [
                            {"type": "string", "format": "uri"},
                            {"$ref": "#/definitions/sourceLink"}
                        ]
                    }
                },
                "createDuplicateEntries": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "allOf": [
                            {"$ref": "#/definitions/os"},
                            {"type": "object", "properties": {"createDuplicateEntries": false}}
                        ]
                    }
                },
                "sdks": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                            "beta": {"type": "boolean"},
                            "build": {"type": "string"},
                            "buildId": {"type": "string", "format": "uuid"},
                            "osStr": {"type": "string"},
                            "rc": {"type": "boolean"},
                            "version": {"type": "string"}
                        }
                    }
                },
                "appledbWebImage": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "id": {"type": "string"},
                        "align": {"type": "string"}
                    }
                },
                "appledbUrl": {"type": "string"},
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["type", "links", "deviceMap"],
                        "properties": {
                            "type": {"enum": ["ipsw", "ota", "update", "recovery", "sfr", "kdk", "installassistant", "combo", "pkg", "aar", "dmg", "exe", "appx", "apk", "xip", "tar", "bin", "ipa", "xpi", "msi", "zip", "smi"]},
                            "arch": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "deviceMap": {"$ref": "#/definitions/os/properties/deviceMap"},
                            "boardMap": {
                                "type": "array",
                                "minItems": 1,
                                "items": {"type": "string"},
                                "uniqueItems": true
                            },
                            "osMap": {"$ref": "#/definitions/os/properties/osMap"},
                            "skipUpdateLinks": {"type": "boolean"},
                            "windowsUpdateDetails": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "updateId": {"type": "string", "format": "uuid"},
                                    "revisionId": {"type": "string", "pattern": "^\\w+$"}
                                }
                            },
                            "hashes": {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "md5":      { "type": "string", "pattern": "^[0-9a-f]{32}$" },
                                    "sha1":     { "type": "string", "pattern": "^[0-9a-f]{40}$" },
                                    "sha2-256": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
                                    "sha2-512": { "type": "string", "pattern": "^[0-9a-f]{128}$" }
                                }
                            },
                            "links": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "$ref": "#/definitions/sourceLink"
                                }
                            },
                            "prerequisiteBuild": {
                                "anyOf": [
                                    {"type": "string"},
                                    {"type": "array", "minItems": 1, "items": {"type": "string"}}
                                ]
                            },
                            "systemImageId": {"type": "string", "format": "uuid"},
                            "size": {"type": "integer"}
                        }
                    }
                }
            }
        },
        "sourceLink": {
            "type": "object",
            "additionalProperties": false,
            "required": ["url", "active"],
            "properties": {
                "url": {"type": "string", "format": "uri"},
                "decryptionKey": {"type": "string"},
                "active": {"type": "boolean"},
                "catalog": {"enum": ["dev-beta", "public-beta"]}
            }
        }
    }
}

=== littlebyteorg/appledb/osFiles/tvOS/13x - 9.x/13Y5752a.json
{
    "osStr": "tvOS",
    "version": "9.2.1 beta",
    "build": "13Y5752a",
    "buildTrain": "FernSeed",
    "released": "2016-04-06",
    "beta": true,
    "deviceMap": [
        "AppleTV5,3"
    ],
    "sources": [
        {
            "type": "ipsw",
            "deviceMap": [
                "AppleTV5,3"
            ],
            "links": [
                {
                    "url": "https://developer.apple.com/services-account/download?path=/iOS/tvOS_9.2.1_beta_Restore_Image/AppleTV53_9.2.1_13Y5752a_Restore.ipsw",
                    "active": false
                }
            ],
            "size": 1145053486
        },
        {
            "type": "ota",
            "deviceMap": [
                "AppleTV5,3"
            ],
            "links": [
                {
                    "url": "http://appldnld.apple.com/tvosseeds/031-56520-20160406-7D09A73C-FAC2-11E5-BD98-BAE2016A2A1A/com_apple_MobileAsset_SoftwareUpdate/1e9069bef79ee17ad74f5ec3836b1a5914f63413.zip",
                    "active": true
                }
            ],
            "hashes": {
                "md5": "5b9728c163d71d73d78bb717878a1e93"
            },
            "size": 855495243
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Software/Safari/26.x/622A69.json
{
    "osStr": "Safari",
    "version": "26.0 beta 6",
    "build": "622A69",
    "buildTrain": "SafariCheerSequoia",
    "released": "2025-09-02",
    "beta": true,
    "releaseNotes": {
        "url": "https://developer.apple.com/services-account/download?path=/Safari/Safari_26.0_for_macOS_Sonoma_and_Safari_26.0_for_macOS_Sequoia_beta_6/Safari_26.0_Beta_6_Notes.pdf",
        "active": false
    },
    "deviceMap": [
        "Safari (macOS)"
    ],
    "osMap": [
        "macOS 15"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 15"
            ],
            "links": [
                {
                    "url": "https://developer.apple.com/services-account/download?path=/Safari/Safari_26.0_for_macOS_Sonoma_and_Safari_26.0_for_macOS_Sequoia_beta_6/Safari_26.0_for_macOS_Sequoia_beta_6.dmg",
                    "active": false
                }
            ],
            "size": 225401695
        },
        {
            "type": "pkg",
            "deviceMap": [
                "Safari (macOS)"
            ],
            "osMap": [
                "macOS 15"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/52/20/093-30896-A_YEJI61SEPT/a9h2hjf8ynvcapy4qkxg1hdanmdlf25w28/Safari26.0SequoiaAutoSeed.pkg",
                    "active": false
                }
            ],
            "hashes": {
                "md5": "dc3861ac4d9ca48563f5a92d1cb0d58d",
                "sha1": "586b5f0d612853cd9bf32fa40b514d259ff2b32a",
                "sha2-256": "3c2be3a1db07166c9251ed8ca17cbb5348d105f85dbf2e71dbaf20897d58d808"
            },
            "size": 225710640
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Simulators/watchOS/20x - 9.x/20S75.json
{
    "osStr": "watchOS",
    "version": "9.1 Simulator",
    "build": "20S75",
    "buildId": "5BB16920-49FE-11ED-8FA8-A42D29C4FC2C",
    "uniqueBuild": "20S75-sim",
    "released": "2022-10-24",
    "createDuplicateEntries": [
        {
            "version": "9.1 RC Simulator",
            "uniqueBuild": "20S75-RC-sim",
            "released": "2022-10-18",
            "rc": true,
            "sources": [
                {
                    "type": "dmg",
                    "deviceMap": [
                        "watchOS Simulator"
                    ],
                    "links": [
                        {
                            "url": "https://developer.apple.com/services-account/download?path=/Developer_Tools/watchOS_9.1_Simulator_Runtime_Release_Candidate/watchOS_9.1_Simulator_Runtime_Release_Candidate.dmg",
                            "active": true
                        }
                    ],
                    "size": 3627381860
                }
            ]
        }
    ],
    "deviceMap": [
        "watchOS Simulator"
    ],
    "sources": [
        {
            "type": "dmg",
            "deviceMap": [
                "watchOS Simulator"
            ],
            "links": [
                {
                    "url": "https://developer.apple.com/services-account/download?path=/Developer_Tools/watchOS_9.1_Simulator_Runtime/watchOS_9.1_Simulator_Runtime.dmg",
                    "active": true
                }
            ],
            "size": 3627381860
        }
    ]
}

=== littlebyteorg/appledb/osFiles/Simulators/visionOS/23x - 26.x/23N47.json
{
    "osStr": "visionOS",
    "version": "26.1 Simulator",
    "build": "23N47",
    "buildId": "AAA31D80-B09E-11F0-A4A5-D99BBE9904DE",
    "uniqueBuild": "23N47-sim",
    "released": "2025-11-03",
    "createDuplicateEntries": [
        {
            "version": "26.1 RC Simulator",
            "uniqueBuild": "23N47-RC-sim",
            "released": "2025-10-28",
            "rc": true
        }
    ],
    "deviceMap": [
        "visionOS Simulator"
    ],
    "sources": [
        {
            "type": "aar",
            "arch": [
                "arm64",
                "x86_64"
            ],
            "systemImageId": "2E54ADF9-2552-4424-B9DE-70ACA6A731B8",
            "deviceMap": [
                "visionOS Simulator"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2025/mobileassets/043-52972/E04B1891-4176-425D-B166-73B2C17954A1/com_apple_MobileAsset_xrOSSimulatorRuntime/C89DFB4A-237E-4F99-AEF3-1C329F089EDF.aar",
                    "decryptionKey": "STa2dlVMIf2jloDiTyG63A43ni0n1EKgFcfvYLcUMvk=",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "36d448112d520cc894e0de2d48a3a6dde7a22781",
                "sha2-256": "e3f3ed73844dd9c5a9ed6084769f969f0b63a05a738ca08587fe1c8226229a82"
            },
            "size": 9126805504
        },
        {
            "type": "aar",
            "arch": [
                "arm64"
            ],
            "systemImageId": "B6EEEE14-082B-4A88-AE85-77F6C266581C",
            "deviceMap": [
                "visionOS Simulator"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2025/mobileassets/043-52973/95746843-4683-451D-9173-273ABC63B794/com_apple_MobileAsset_xrOSSimulatorRuntime/7F705F5A-6E47-4EEA-ABB9-E0B953E6F5DF.aar",
                    "decryptionKey": "80J/2BO2hWPNODxLzEJP3ROhOutqhkhn7SRDVGqtJ8o=",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "9d25ee7a6e82aac885c48f6e83526f0801793898",
                "sha2-256": "ffd9635befadb39718cabd8dbdd2f85ce1b7cce9cffc0b47f7554251d87b7deb"
            },
            "size": 7180648448
        }
    ]
}

=== littlebyteorg/appledb/osFiles/bridgeOS/18x - 5.x/18P54646b.json
{
    "osStr": "bridgeOS",
    "version": "5.4 beta",
    "build": "18P54646b",
    "restoreVersion": "18.16.14646.5.2,0",
    "buildId": "58E627E2-9C14-11EB-AD5D-BF571F136069",
    "buildTrain": "GoldenGateBridgeFSeed",
    "released": "2021-04-21",
    "beta": true,
    "deviceMap": [
        "iBridge2,1",
        "iBridge2,3",
        "iBridge2,4",
        "iBridge2,5",
        "iBridge2,6",
        "iBridge2,7",
        "iBridge2,8",
        "iBridge2,10",
        "iBridge2,12",
        "iBridge2,14",
        "iBridge2,15",
        "iBridge2,16",
        "iBridge2,19",
        "iBridge2,20",
        "iBridge2,21",
        "iBridge2,22"
    ],
    "sources": [
        {
            "type": "pkg",
            "systemImageId": "59157BF2-329E-4BFB-B6AA-AEA54CE19FB2",
            "deviceMap": [
                "iBridge2,1",
                "iBridge2,3",
                "iBridge2,4",
                "iBridge2,5",
                "iBridge2,6",
                "iBridge2,7",
                "iBridge2,8",
                "iBridge2,10",
                "iBridge2,12",
                "iBridge2,14",
                "iBridge2,15",
                "iBridge2,16",
                "iBridge2,19",
                "iBridge2,20",
                "iBridge2,21",
                "iBridge2,22"
            ],
            "links": [
                {
                    "url": "https://swcdn.apple.com/content/downloads/60/26/071-29401-A_BTAO0AKEJ3/8e68jv2nbeljac66e9r8r9oe3s60dddy30/BridgeOSUpdateCustomer.pkg",
                    "active": false
                }
            ],
            "size": 464929377
        }
    ]
}

=== littlebyteorg/appledb/osFiles/visionOS/21x - 1.x/21O5761a.json
{
    "osStr": "visionOS",
    "version": "1.3 beta 3",
    "build": "21O5761a",
    "restoreVersion": "21.15.761.5.1,0",
    "buildId": "DB40E8A8-378E-11EF-99EC-D327F2CC4AD1",
    "buildTrain": "BorealisGSeed",
    "released": "2024-07-09",
    "beta": true,
    "deviceMap": [
        "RealityDevice14,1"
    ],
    "sources": [
        {
            "type": "ipsw",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/fullrestores/062-28277/9AF374CC-6D65-4B59-9C60-FD69691D4AB6/Apple_Vision_Pro_1.3_21O5761a_Restore.ipsw",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "fd0f41beddef3f1369066405cd201ff0e166c6b8",
                "sha2-256": "02480bb499944763bc11dccdeaae51d7e04b14568b35c1ecf50a855b1641d053"
            },
            "size": 9187698657
        },
        {
            "type": "ota",
            "systemImageId": "A1B8D936-0385-4A25-A6E0-30EA74AC2705",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28281/AF732DE9-E2AE-4A34-A367-C948D47B677B/com_apple_MobileAsset_SoftwareUpdate/2f1c6a740965c75b5bec8f3ef98cb2d2782c5942.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "8332c783eb70c459efde261577a7f056972ea9a8",
                "sha2-256": "4b80a675c71d0048bd7425f57491a35fef3fd2009614378d2bdb7b9c40f96c73"
            },
            "size": 7538272937
        },
        {
            "type": "ota",
            "prerequisiteBuild": "21O5587a",
            "systemImageId": "A1B8D936-0385-4A25-A6E0-30EA74AC2705",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28279/17D4A1DD-DCB6-4B71-83E3-50136BCEBBF8/com_apple_MobileAsset_SoftwareUpdate/2e25726f98a2359f81c58efc7b637d3c2c93a96b.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "20877e7b945ae7a2dbeb1696130c20d2070250ab",
                "sha2-256": "e0baa9d3c598a70344a00071beb25344e95eb2a191d7cb9fabfae61cf5ce63ac"
            },
            "size": 1414257788
        },
        {
            "type": "ota",
            "prerequisiteBuild": "21O5756a",
            "systemImageId": "A1B8D936-0385-4A25-A6E0-30EA74AC2705",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28734/DB8017DD-826A-4EC2-B29D-A49C0CD8DA6B/com_apple_MobileAsset_SoftwareUpdate/21a964ca852941ebc7c54a6f225f4bf166d110d8.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "e7d3f116913bd90a67af3fe13583cd3b3268c6bc",
                "sha2-256": "6e29c1bc6a94bdf091553ed70e4443800b9496d792df236c8ed390745a35f14c"
            },
            "size": 668616020
        },
        {
            "type": "recovery",
            "systemImageId": "3C15130B-7EE4-4425-81EB-27448B56DD97",
            "deviceMap": [
                "RealityDevice14,1"
            ],
            "links": [
                {
                    "url": "https://updates.cdn-apple.com/2024SpringSeed/patches/062-28278/3BA6AB2E-C9C0-4A83-8DF2-2996BC3CE7ED/com_apple_MobileAsset_RecoveryOSUpdate/38a3553014272421168a0a1e178403cdea27b210.zip",
                    "active": true
                }
            ],
            "hashes": {
                "sha1": "0b1622353a2d5f4a7a51c067840e807774009392",
                "sha2-256": "92e043e9167d8c9d29a6341cb9391210d91ea3cd89d047fd803999bd91e00bf3"
            },
            "size": 194258088
        }
    ]
}
